part1: part1.c #this rule makes part 1 compile. 
	@echo "-------------------------------------------"
	@echo "Compiling..."
	@gcc -o test part1.c -lm
	@./test

part2: part2.c #this rule makes part 2 compile.
	@echo "-------------------------------------------"
	@echo "Compiling..."
	@gcc -o test part2.c
	@./test

clean: #cleans.
	@echo "-------------------------------------------"
	@echo "Cleaning..."
	@rm -f *.o
	@rm -f test
